name: 'Setup Python with uv'
description: 'Install Python via uv and setup dependencies'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ -f pyproject.toml ]; then
          uv sync --all-extras --dev
        elif [ -f requirements.txt ]; then
          uv pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then uv pip install -r requirements-dev.txt; fi
        fi
