name: 'Docker Build'
description: 'Build and push Docker image with SHA-based skip (supports Docker and Podman)'

inputs:
  registry:
    description: 'Container registry'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Image name (defaults to repo name)'
    required: false
  sha:
    description: 'Commit SHA for tagging'
    required: true
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  tag-prefix:
    description: 'Tag prefix to strip for semver extraction (e.g. "session-manager/")'
    required: false
    default: ''
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'

outputs:
  image-exists:
    description: 'Whether image already existed'
    value: ${{ steps.check.outputs.exists }}
  tags:
    description: 'Applied tags'
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: 'composite'
  steps:
    - name: Compute image reference
      id: image-ref
      shell: bash
      run: |
        if [ -n "${{ inputs.image-name }}" ]; then
          echo "name=${{ github.repository_owner }}/${{ inputs.image-name }}" >> $GITHUB_OUTPUT
        else
          echo "name=${{ github.repository }}" >> $GITHUB_OUTPUT
        fi

    - name: Detect builder
      id: detect
      shell: bash
      run: |
        if command -v podman &>/dev/null; then
          echo "builder=podman" >> $GITHUB_OUTPUT
        elif command -v docker &>/dev/null; then
          echo "builder=docker" >> $GITHUB_OUTPUT
        else
          echo "::error::No container builder found (need docker or podman)"
          exit 1
        fi

    - name: Check if image exists
      id: check
      shell: bash
      run: |
        IMAGE="${{ inputs.registry }}/${{ steps.image-ref.outputs.name }}"
        TAG="${{ inputs.sha }}"
        BUILDER="${{ steps.detect.outputs.builder }}"
        if $BUILDER manifest inspect ${IMAGE}:${TAG} > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      if: steps.check.outputs.exists != 'true' && steps.detect.outputs.builder == 'docker'
      uses: docker/setup-buildx-action@v3

    - name: Compute clean version
      if: startsWith(github.ref, 'refs/tags/')
      id: clean-ref
      shell: bash
      run: |
        REF_NAME="${GITHUB_REF_NAME}"
        PREFIX="${{ inputs.tag-prefix }}"
        echo "version=${REF_NAME#$PREFIX}" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ steps.image-ref.outputs.name }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest,enable={{is_default_branch}}
          type=semver,pattern={{version}},value=${{ steps.clean-ref.outputs.version || '' }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.clean-ref.outputs.version || '' }}
          type=semver,pattern={{major}},value=${{ steps.clean-ref.outputs.version || '' }},enable=${{ !startsWith(steps.clean-ref.outputs.version || 'v1', 'v0.') }}

    - name: Build and push (Docker)
      if: steps.check.outputs.exists != 'true' && inputs.push == 'true' && steps.detect.outputs.builder == 'docker'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push (Podman)
      if: steps.check.outputs.exists != 'true' && inputs.push == 'true' && steps.detect.outputs.builder == 'podman'
      shell: bash
      env:
        META_TAGS: ${{ steps.meta.outputs.tags }}
        META_LABELS: ${{ steps.meta.outputs.labels }}
      run: |
        # Build tag flags
        TAG_ARGS=()
        while IFS= read -r tag; do
          [ -n "$tag" ] && TAG_ARGS+=("-t" "$tag")
        done <<< "$META_TAGS"

        # Build label flags
        LABEL_ARGS=()
        while IFS= read -r label; do
          [ -n "$label" ] && LABEL_ARGS+=("--label" "$label")
        done <<< "$META_LABELS"

        echo "Building with ${#TAG_ARGS[@]/2} tag(s)"
        podman build \
          --file "${{ inputs.dockerfile }}" \
          "${TAG_ARGS[@]}" \
          "${LABEL_ARGS[@]}" \
          .

        # Push each tag
        while IFS= read -r tag; do
          [ -n "$tag" ] && podman push "$tag"
        done <<< "$META_TAGS"

    - name: Retag existing image (Docker)
      if: steps.check.outputs.exists == 'true' && inputs.push == 'true' && steps.detect.outputs.builder == 'docker'
      shell: bash
      run: |
        SOURCE="${{ inputs.registry }}/${{ steps.image-ref.outputs.name }}:${{ inputs.sha }}"
        TAGS="${{ steps.meta.outputs.tags }}"
        TAG_ARGS=""
        for tag in $TAGS; do
          TAG_ARGS="${TAG_ARGS} -t ${tag}"
        done
        docker buildx imagetools create ${TAG_ARGS} ${SOURCE}

    - name: Retag existing image (Podman)
      if: steps.check.outputs.exists == 'true' && inputs.push == 'true' && steps.detect.outputs.builder == 'podman'
      shell: bash
      env:
        META_TAGS: ${{ steps.meta.outputs.tags }}
      run: |
        SOURCE="${{ inputs.registry }}/${{ steps.image-ref.outputs.name }}:${{ inputs.sha }}"
        podman pull "$SOURCE"
        while IFS= read -r tag; do
          if [ -n "$tag" ] && [ "$tag" != "$SOURCE" ]; then
            podman tag "$SOURCE" "$tag"
            podman push "$tag"
          fi
        done <<< "$META_TAGS"
